### ISSUE TITLE
Analyze and compare the log management tools in the market

### ISSUE THREAD

**Issue by sitilge** [Rpc-h/applications-platform#30]

**Comment by Teebor-Choka** [comment]
It should be noted that Graylog highly utilized the Elasticsearch ecosystem and the newer versions have upgraded to the OpenSearch ecosystem.

**Comment by ausias-armesto** [comment]
Here I add my contribution
- We should center to choose the tool that best suits to developers and testers, which will be the ones using it.
- Here are two articles for comparison with little valuable information.
   - https://stackshare.io/stackups/graylog-vs-loki
   - https://www.trustradius.com/compare-products/grafana-loki-vs-graylog 
- This other article is more valuable by the arguments that it provides: https://thechief.io/c/editorial/kubernetes-logging-tools-a-comparison/
