### ISSUE TITLE
Grafana Hopr node needs a cpu panel

### ISSUE THREAD

**Issue by esterlus** [Rpc-h/applications-platform#71]
## HOPR/Hoprd Node

In order to better understand network health the mentioned grafana view should contain a CPU system load panel.

**Comment by ausias-armesto** [comment]
the new **Hoprd Node ** dashboard in Grafana contains much more metrics which will help developers to better understand the insights of the running node
https://grafana.prod.hoprtech.net/d/d9OUo4D4z/hoprd-node?orgId=1

Keep in mind, that Rpch hoprd nodes are now monitored in Core Team grafana.
